version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  frontend:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - frontend:/usr/src/app
    links:
      - backend
    depends_on:
      - backend

  backend:
    image: node:latest
    volumes:
      - backend:/usr/src/app
    links:
      - redis
    depends_on:
      - redis

  worker:
    image: node:latest
    volumes:
      - worker:/usr/src/app
    links:
      - redis
    depends_on:
      - redis

volumes:
  redis-data:
  frontend:
  backend:
  worker:

networks:
  default:
    external:
      name: my-network